// src/pages/OurImpact.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  FiGlobe, 
  FiHome, 
  FiDollarSign, 
  FiUsers, 
  FiTrendingUp, 
  FiBarChart2, 
  FiHeart,
  FiMap,
  FiDroplet,
  FiSun,
  FiBookOpen
} from 'react-icons/fi';

const OurImpact = () => {
  const [activeTab, setActiveTab] = useState('economic');

  const impactData = {
    economic: [
      {
        title: "Youth Enterprises Supported",
        description: "Youth-led businesses launched through our entrepreneurship programs.",
        value: "48+",
        label: "In Tana River County",
        icon: <FiTrendingUp className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Sustainable Jobs Created",
        description: "Employment opportunities generated through our initiatives.",
        value: "620+",
        label: "Livelihoods transformed",
        icon: <FiUsers className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Income Generated",
        description: "Cumulative revenue generated by supported youth businesses.",
        value: "$380K+",
        label: "Economic boost",
        icon: <FiBarChart2 className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Agricultural Projects",
        description: "Community farming initiatives supported across the county.",
        value: "27",
        label: "Food security programs",
        icon: <FiSun className="w-6 h-6 text-emerald-600" />,
      },
    ],
    community: [
      {
        title: "Water Access Points",
        description: "Clean water sources established in remote communities.",
        value: "15",
        label: "Serving 8,000+ people",
        icon: <FiDroplet className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Education Centers",
        description: "Learning facilities built or renovated across Tana River.",
        value: "9",
        label: "Serving 2,500+ youth",
        icon: <FiBookOpen className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Healthcare Outreach",
        description: "Medical camps conducted in underserved communities.",
        value: "32",
        label: "15,000+ patients served",
        icon: <FiHeart className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Peace Initiatives",
        description: "Community dialogues fostering inter-ethnic harmony.",
        value: "18",
        label: "Across 6 sub-counties",
        icon: <FiUsers className="w-6 h-6 text-emerald-600" />,
      },
    ],
    environment: [
      {
        title: "Trees Planted",
        description: "Native species planted to combat desertification.",
        value: "42,000+",
        label: "Along Tana River basin",
        icon: <FiGlobe className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Water Conservation",
        description: "Rainwater harvesting systems installed.",
        value: "120",
        label: "In schools and villages",
        icon: <FiDroplet className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Sustainable Farming",
        description: "Farmers trained in climate-resilient agriculture.",
        value: "850+",
        label: "Adopting new techniques",
        icon: <FiSun className="w-6 h-6 text-emerald-600" />,
      },
      {
        title: "Renewable Energy",
        description: "Solar installations in community facilities.",
        value: "22",
        label: "Providing clean power",
        icon: <FiSun className="w-6 h-6 text-emerald-600" />,
      },
    ]
  };

  const testimonials = [
    {
      author: "Amina Yusuf",
      role: "Entrepreneur, Tana Delta",
      quote: "The business training helped me start my fish processing venture. I now employ 5 others from my community.",
      image: "profile1",
    },
    {
      author: "Mohamed Abdi",
      role: "Farmer, Garsen",
      quote: "With drip irrigation training, my farm now produces year-round despite the dry climate. My income has tripled!",
      image: "profile2",
    },
    {
      author: "Fatuma Hassan",
      role: "Youth Leader, Bura",
      quote: "Our peace initiative brought together different communities. For the first time, we have a shared vision for development.",
      image: "profile3",
    },
    {
      author: "James Kiprop",
      role: "Teacher, Hola",
      quote: "The new learning center has transformed education in our area. Attendance has doubled and our students are thriving.",
      image: "profile4",
    },
  ];

  return (
       
    <motion.div
      initial={{ opacity: 0, y: 20 }}       // Start invisible and slightly below
      animate={{ opacity: 1, y: 0 }}        // End visible and in position
      transition={{ duration: 1 }}          // Animation duration = 1 second
    >


    <div className="min-h-screen bg-gradient-to-b from-white to-emerald-50">
      {/* Hero Section */}
      <div className="relative h-[70vh] overflow-hidden">
        <div className="absolute inset-0 bg-black opacity-50 z-10"></div>
        <div 
          className="absolute inset-0 bg-cover bg-center z-0"
          style={{ backgroundImage: "url('src/images/WhatsApp Image 2025-06-17 at 5.20.07 PM.jpeg')" }}
        ></div>
        
        <div className="relative z-20 h-full flex flex-col justify-center">
          <div className="max-w-6xl mx-auto px-4 text-center text-white">
            <div className="inline-flex items-center justify-center bg-emerald-600 bg-opacity-80 text-white rounded-full p-3 mb-6">
              <FiMap className="w-8 h-8" />
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight">
              Transforming <span className="text-emerald-300">Tana River County</span>
            </h1>
            <p className="text-xl md:text-2xl max-w-3xl mx-auto mb-8">
              Creating sustainable impact through community-led initiatives in Kenya's coastal region
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <button className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-8 rounded-full transition duration-300 transform hover:scale-105">
                Our Initiatives
              </button>
              <button className="bg-white text-emerald-700 hover:bg-emerald-100 font-bold py-3 px-8 rounded-full transition duration-300 transform hover:scale-105">
                Partner With Us
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Impact Overview */}
      <section className="py-16 bg-white">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">Our Impact in Tana River</h2>
            <div className="w-24 h-1 bg-emerald-500 mx-auto mb-6"></div>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Since 2018, we've worked hand-in-hand with Tana River communities to create sustainable change. 
              Our approach focuses on empowering local leadership and building resilience in this unique ecosystem.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-gradient-to-br from-emerald-50 to-white rounded-2xl border border-emerald-100 p-8 text-center shadow-sm hover:shadow-md transition-all">
              <div className="text-5xl font-bold text-emerald-700 mb-4">6+</div>
              <h3 className="text-xl font-bold text-gray-800 mb-3">Years of Commitment</h3>
              <p className="text-gray-600">
                Continuously serving Tana River communities since 2018
              </p>
            </div>
            
            <div className="bg-gradient-to-br from-emerald-50 to-white rounded-2xl border border-emerald-100 p-8 text-center shadow-sm hover:shadow-md transition-all">
              <div className="text-5xl font-bold text-emerald-700 mb-4">24</div>
              <h3 className="text-xl font-bold text-gray-800 mb-3">Communities Reached</h3>
              <p className="text-gray-600">
                Serving villages across Tana River's diverse landscape
              </p>
            </div>
            
            <div className="bg-gradient-to-br from-emerald-50 to-white rounded-2xl border border-emerald-100 p-8 text-center shadow-sm hover:shadow-md transition-all">
              <div className="text-5xl font-bold text-emerald-700 mb-4">65K+</div>
              <h3 className="text-xl font-bold text-gray-800 mb-3">Lives Touched</h3>
              <p className="text-gray-600">
                Creating positive change for residents of all ages
              </p>
            </div>
          </div>
          
          <div className="mt-16 bg-gradient-to-r from-emerald-600 to-green-700 rounded-2xl p-1 shadow-xl">
            <div className="bg-white rounded-xl p-8 md:p-12 flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 mb-8 md:mb-0">
                <h3 className="text-2xl font-bold text-gray-800 mb-4">Tana River at a Glance</h3>
                <p className="text-gray-600 mb-6">
                  Tana River County, named after Kenya's longest river, is home to diverse communities including the Pokomo, Orma, and Wardei. 
                  Despite challenges like seasonal flooding and droughts, its people demonstrate remarkable resilience.
                </p>
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <div className="bg-emerald-100 p-1 rounded-full mr-3 mt-1">
                      <FiGlobe className="w-4 h-4 text-emerald-600" />
                    </div>
                    <span>Population: 315,943 (2019 Census)</span>
                  </li>
                  <li className="flex items-start">
                    <div className="bg-emerald-100 p-1 rounded-full mr-3 mt-1">
                      <FiHome className="w-4 h-4 text-emerald-600" />
                    </div>
                    <span>Main economic activities: Farming, fishing, livestock</span>
                  </li>
                  <li className="flex items-start">
                    <div className="bg-emerald-100 p-1 rounded-full mr-3 mt-1">
                      <FiDroplet className="w-4 h-4 text-emerald-600" />
                    </div>
                    <span>Tana River provides 80% of Nairobi's water supply</span>
                  </li>
                </ul>
              </div>
              <div className="md:w-1/2 flex justify-center">
                <div className="relative">
                  <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-64 md:h-80" />
                  <div className="absolute bottom-4 left-4 bg-emerald-700 text-white px-4 py-2 rounded-lg">
                    Tana River County Map
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Impact Tabs */}
      <section className="py-16 bg-gradient-to-b from-emerald-50 to-white">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">Our Impact Areas</h2>
            <div className="w-24 h-1 bg-emerald-500 mx-auto mb-6"></div>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Holistic development addressing Tana River's unique challenges and opportunities
            </p>
          </div>
          
          {/* Tab Navigation */}
          <div className="flex flex-wrap justify-center gap-2 mb-12">
            <button
              className={`px-6 py-3 rounded-full font-medium transition-all ${
                activeTab === 'economic' 
                  ? 'bg-emerald-600 text-white shadow-lg' 
                  : 'bg-white text-gray-700 hover:bg-gray-100 border border-gray-200'
              }`}
              onClick={() => setActiveTab('economic')}
            >
              Economic Empowerment
            </button>
            <button
              className={`px-6 py-3 rounded-full font-medium transition-all ${
                activeTab === 'community' 
                  ? 'bg-emerald-600 text-white shadow-lg' 
                  : 'bg-white text-gray-700 hover:bg-gray-100 border border-gray-200'
              }`}
              onClick={() => setActiveTab('community')}
            >
              Community Development
            </button>
            <button
              className={`px-6 py-3 rounded-full font-medium transition-all ${
                activeTab === 'environment' 
                  ? 'bg-emerald-600 text-white shadow-lg' 
                  : 'bg-white text-gray-700 hover:bg-gray-100 border border-gray-200'
              }`}
              onClick={() => setActiveTab('environment')}
            >
              Environmental Sustainability
            </button>
          </div>
          
          {/* Tab Content */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {impactData[activeTab].map((impact, index) => (
              <div 
                key={index} 
                className="bg-white rounded-2xl border border-emerald-100 shadow-md p-6 transition-all duration-300 hover:shadow-lg hover:border-emerald-300"
              >
                <div className="mb-4">
                  <div className="bg-emerald-100 p-3 rounded-full inline-block">
                    {impact.icon}
                  </div>
                </div>
                <h3 className="text-xl font-bold text-gray-800 mb-3">{impact.title}</h3>
                <p className="text-gray-600 mb-6">{impact.description}</p>
                <div className="border-t border-emerald-100 pt-4">
                  <div className="text-3xl font-bold text-emerald-700">{impact.value}</div>
                  <div className="text-gray-600">{impact.label}</div>
                </div>
              </div>
            ))}
          </div>
          
          {/* ROI Section */}
          <div className="mt-16 max-w-5xl mx-auto">
            <div className="bg-gradient-to-r from-emerald-600 to-green-700 text-white rounded-2xl p-8 shadow-xl">
              <div className="flex flex-col md:flex-row items-center gap-8">
                <div className="md:w-2/3">
                  <h3 className="text-2xl font-bold mb-4">Return on Community Investment</h3>
                  <p className="mb-6 opacity-90">
                    For every $1 invested in Tana River programs, we generate $8.40 in economic and social value through 
                    increased employment, agricultural productivity, and community resilience.
                  </p>
                  <div className="flex items-center gap-4">
                    <div className="text-4xl font-bold">1:8.4</div>
                    <div className="opacity-80">ROI ratio over 5 years</div>
                  </div>
                </div>
                <div className="md:w-1/3 flex justify-center">
                  <div className="relative">
                    <div className="w-48 h-48 rounded-full border-8 border-emerald-400 border-t-emerald-300 border-r-emerald-300 flex items-center justify-center animate-pulse">
                      <div className="text-center">
                        <div className="text-3xl font-bold">840%</div>
                        <div className="text-sm opacity-80">Return</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-16 bg-white">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">Voices from Tana River</h2>
            <div className="w-24 h-1 bg-emerald-500 mx-auto mb-6"></div>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Hear directly from community members whose lives have been transformed
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {testimonials.map((testimonial, index) => (
              <div 
                key={index} 
                className="bg-gradient-to-br from-emerald-50 to-white rounded-2xl shadow-lg p-6 relative overflow-hidden border border-emerald-100"
              >
                <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-emerald-500 to-green-600"></div>
                <div className="flex items-start">
                  <div className="bg-gray-200 border-2 border-dashed rounded-xl w-16 h-16 flex-shrink-0" />
                  <div className="ml-4">
                    <div className="font-bold text-gray-800">{testimonial.author}</div>
                    <div className="text-emerald-600 text-sm mb-3">{testimonial.role}</div>
                    <p className="text-gray-600 italic">"{testimonial.quote}"</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          {/* Photo Gallery */}
          <div className="mt-16">
            <h3 className="text-2xl font-bold text-gray-800 mb-6 text-center">Life in Tana River</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-48"></div>
              <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-48"></div>
              <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-48"></div>
              <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-48"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Partners Section */}
      <section className="py-16 bg-emerald-50">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-800 mb-4">Our Trusted Partners</h2>
            <div className="w-24 h-1 bg-emerald-500 mx-auto mb-6"></div>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Collaborating with organizations committed to Tana River's development
            </p>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {[1, 2, 3, 4].map((item) => (
              <div key={item} className="bg-white rounded-xl p-6 flex items-center justify-center h-32 shadow-sm hover:shadow-md transition-all">
                <div className="bg-gray-200 border-2 border-dashed rounded-xl w-24 h-24"></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 bg-gradient-to-r from-emerald-600 to-green-800 text-white">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6">Join Our Mission in Tana River</h2>
          <p className="text-xl mb-8 max-w-3xl mx-auto">
            Help us expand our impact and create lasting change for Tana River communities
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <button className="bg-white text-emerald-700 font-bold py-3 px-8 rounded-full hover:bg-gray-100 transition duration-300 transform hover:scale-105">
              Support Our Work
            </button>
            <button className="bg-transparent border-2 border-white text-white font-bold py-3 px-8 rounded-full hover:bg-white hover:bg-opacity-20 transition duration-300 transform hover:scale-105">
              Visit Tana River
            </button>
          </div>
        </div>
      </section>
    </div>
      </motion.div>
  );
};

export default OurImpact;